Refactor putRecursive to avoid getRecursive and updating unchanged assets
hyperledger-labs/cc-tools pull request #32
Opened 2023-09-20 17:24 UTC by mikaellafs

2023-10-27 18:41 UTC, andremacedopv requested changes
@mikaellafs Everything worked fine in my tests here, but is there a reason to maintain the `root` parameter in the `putRecursive` method? I think there is no reason for it there after the refactor

2023-10-27 19:07 UTC, mikaellafs commented
> @mikaellafs Everything worked fine in my tests here, but is there a reason to maintain the `root` parameter in the `putRecursive` method? I think there is no reason for it there after the refactor

Humm you're right, better we remove it

2023-10-27 19:58 UTC, andremacedopv approved these changes

2023-12-12 10:55 UTC, samuelvenzi approved these changes

2023-12-12 11:02 UTC, merged